lsh123/xmlsec

win32/configure.js
configure.in was renamed to configure.in in commit
ba55ea006f1bd8e28a7d8fe9da6b4a64ba00befb (rename configure.in,
2016-02-05) but win32's configure.js was not adapted.
=> win32 configure: adapt to renamed autoconf configure

apps/cmdline.c, apps/crypto.c, apps/xmlsec.c
The error is:
c:\Program Files\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1925): warning C4005: 'snprintf': macro redefinition
..\apps\xmlsec.c(13): note: see previous definition of 'snprintf'
c:\Program Files\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration
1900 is from
<http://stackoverflow.com/questions/70013/how-to-detect-if-im-compiling-code-with-visual-studio-2008>.
=> Fix Visual Studio 2015 build

tests/README, tests/testDSig.sh, tests/testEnc.sh, tests/testrun.sh
I used this local patch when testing the relationship testcase, so I could quickly get feedback if my changes are OK or not OK. Does it make sense to have this upstream?
=> tests: add support for running a single test using XMLSEC_TEST_NAME

src/openssl/x509vfy.c
Seems, certsVerificationDepth was not used at all:
https://github.com/lsh123/xmlsec/search?utf8=%E2%9C%93&q=certsVerificationDepth
Thus, the maximum depth of the certificate chain have not been performed.
=> openssl: fixed verification depth param passing

src/openssl/signatures.c
Without this fix, we fail to compile on CentOS 6.x which lacks ECDSA
support.
=> Fix mismatched conditional for XMLSEC_NO_ECDSA

include/xmlsec/mscrypto/certkeys.h, src/mscrypto/certkeys.c, src/mscrypto/signatures.c
I had problems with signing with RSA-SHA256 algorithm on Windows 7. Cryptographic provider acquired in xmlSecMSCryptoKeyDataAdoptCert function was not able to create hash in xmlSecMSCryptoSignatureExecute function. This commit fixes it for me.
=> fix signing with RSA SHA2 via mscrypto

src/openssl/Makefile.am, src/openssl/app.c, src/openssl/evp.c, src/openssl/kt_rsa.c, src/openssl/openssl11_wrapper.h, src/openssl/signatures.c, src/openssl/x509vfy.c
Tried to get it done as little intrusive as possible. It compiles
against 1.1.0 and 1.0.2h. Testsuite passes/fails in the same way.
Signed-off-by: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>
=> openssl: get it build against openssl 1.1.0 and earlier

configure.ac
- LibreSSL:
* defines OPENSSL_VERSION_NUMBER as 0x20000000L
* deFines LIBRESS_VERSION_NUMBER in opensslv.h
* was forked from 1.0.1f / 0x1000107fL
PR:		https://bugs.freebsd.org/213301
Reported by:	Michael Gmelin <grembo@freebsd.org>
=> configure: Fix LibreSSL version detection

src/relationship.c
According to the libxml documentation, memory returned from xmlGetProp should be freed with xmlFree(). But in relationship.c, xmlFree is not called.
This commit also removes a variable which doesn't make any sense.
=> Fix memory leak caused by xmlGetProp

Makefile.am, configure.ac
This is useful when xmlsec is bundled as a library in a project, and the
additional dependencies needed to build the documentation cause an
overhead, as only the library is used from the build result anyway.
=> configure: add option to disable documentation

Makefile.am, configure.ac
This is useful when xmlsec is bundled as a library in a project, and the
building the documentation cause an overhead, as only the library is
used from the build result anyway.
=> configure: add option to disable applications

apps/xmlsec.c, src/nss/x509.c, src/nss/x509vfy.c, tests/testDSig.sh
Always extract it, just don't verify if the flag is used.
=> nss: fix XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS handling

src/mscrypto/x509.c, src/mscrypto/x509vfy.c
Always extract it, just don't construct the certificate chain if the
flag is used.
With this, the recently added two new testcases in commits
7f6f993c32916cc73f8103ceac928609c0bd9fa0 (nss: fix
XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS handling (#78),
2017-01-22) and 1533729d17da5d35b9d014f85091ad80d54db265 (nss adopt cert
type (#73), 2016-12-15) also pass for mscrypto.
=> mscrypto: fix XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS handling

win32/configure.js
From version.h.in, similarly how autoconf does so.
I've verified that the output is the same as on Linux (modulo unix vs dos line endings).
=> win32 configure: generate version.h

configure.ac, include/xmlsec/nss/crypto.h, include/xmlsec/nss/symbols.h, src/nss/README, src/nss/crypto.c, src/nss/pkikeys.c, src/nss/signatures.c
make check-crypto-nss XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha256-ecdsa-sha256"
now passes after these changes. Other notes:
- the NSS representation of ECDSA keys is ecKey
- the NSS identifier for ECDSA-SHA256 is
SEC_OID_ANSIX962_ECDSA_SHA256_SIGNATURE
- ECDSA has no fixed signature size, as it depends on the curve
parameters. This means the size has to be always told explicitly to
NSS, so DSAU_DecodeDerSig() -> DSAU_DecodeDerSigToLen(),
DSAU_EncodeDerSig() -> DSAU_EncodeDerSigWithLen().
- the full list of supported ECDSA parameters is at e.g. NSS ecdecode.c,
EC_FillParams():
https://dxr.mozilla.org/nss/source/nss/lib/freebl/ecdecode.c#214
=> nss: add ECDSA-SHA256 support

include/xmlsec/nss/crypto.h, include/xmlsec/nss/symbols.h, src/nss/crypto.c, src/nss/signatures.c
make check-crypto-nss XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha1-ecdsa-sha1"
passes with this. The only (perhaps) non-trivial part is that I pulled a duplicated list of conditions to a separate function.
=> nss: add ECDSA-SHA1 support

include/xmlsec/nss/crypto.h, include/xmlsec/nss/symbols.h, src/nss/crypto.c, src/nss/signatures.c
make check-crypto-nss XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha512-ecdsa-sha512"
passes with these changes. Also, I think with this finally the nss backend is on par with the openssl one regarding ECDSA support.
=> nss: add ECDSA-SHA512 supports

src/nss/signatures.c
Due to reading uninitialized memory. gdb says:
Assertion failure: dest == NULL || dest->data == NULL, at secasn1e.c:1483
Program received signal SIGABRT, Aborted.
0x00007ffff74748d7 in raise () from /lib64/libc.so.6
(gdb) up
#1  0x00007ffff7475caa in abort () from /lib64/libc.so.6
(gdb)
#2  0x00007fffe57f96ae in PR_Assert (s=0x7fffe1cbf298 "dest == NULL || dest->data == NULL", file=0x7fffe1cbef60 "secasn1e.c", ln=1483) at ../../../../pr/src/io/prlog.c:553
553         abort();
(gdb)
#3  0x00007fffe1cb1941 in SEC_ASN1EncodeItem_Util (poolp=0x0, dest=0x7fffffff95f0, src=0x7fffffff9530, theTemplate=0x7fffe55ae180 <DSA_SignatureTemplate>) at secasn1e.c:1483
1483        PORT_Assert(dest == NULL || dest->data == NULL);
=> nss: fix assert when building against debug nss

src/openssl/x509.c, src/openssl/x509vfy.c
make check-crypto-openssl XMLSEC_TEST_NAME="enveloping-sha256-rsa-sha256-verify"
passes with this, similary to nss and mscrypto.
=> openssl: fix XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS handling

src/gnutls/x509.c, src/gnutls/x509vfy.c
make check-crypto-gnutls XMLSEC_TEST_NAME="enveloping-sha256-rsa-sha256-verify"
passes with this. Now all backends handle this flag the same way.
=> gnutls: fix XMLSEC_KEYINFO_FLAGS_X509DATA_DONT_VERIFY_CERTS handling

src/nss/x509.c, src/transforms.c
In all 3 cases the variables are written again a few lines later. The
only purpose could be if xmlSecBufferGetSize() would have a side effect,
which is not the case.
Found by the clang static analyzer.
=> Remove never read variable assignments

apps/xmlsec.c, include/xmlsec/xmlsec.h, src/parser.c, src/xmlsec.c
From https://github.com/lsh123/xmlsec/issues/43
=> attempt XXE prevention using custom external entity loader

apps/xmlsec.c, src/bn.c
This allows less indentation, so makes the code more readable.
(OTOH this is a bit of a cosmetic change, if you don't like it, no hard feelings. :-) )
=> Eliminate unnecessary else branches after return statements

include/xmlsec/xmltree.h, src/bn.c, src/gcrypt/asymkeys.c, src/gnutls/x509.c, src/mscrypto/x509.c, src/nss/bignum.c, src/nss/x509.c, src/openssl/bn.c, src/openssl/x509.c, src/xmltree.c
When xmlsec creates XML nodes in the tree, it adds "\n" automatically. Functions `xmlSecSetDefaultLineFeed()` and `xmlSecGetDefaultLineFeed()` allow users to change this default functionality. I've use `xmlSecBase64GetDefaultLineSize()` and `xmlSecBase64SetDefaultLineSize()` as a template for this.
This may be necessary for some projects. For example the Brazillian government [NFE Project](https://www.nfe.fazenda.gov.br/portal/listaConteudo.aspx?tipoConteudo=33ol5hhSYZk=) requires xml signatures and doesn't allow linebreaks between tags in messages. I think it would be helpful to have this function.
Please let me know if I should change something in this code to be accepted.
=> Add Default linefeed for xmltree module

configure.ac
If these are already set, then still check for the version, but no need
to invoke pkg-config or xml2-config.
This is an attempt to upstream the first 3 hunks of <https://github.com/LibreOffice/core/blob/master/external/libxmlsec/xmlsec1-configure.patch.1#L52>.
=> configure: consider already set LIBXML_CFLAGS / LIBXML_LIBS

include/xmlsec/nss/crypto.h, src/nss/crypto.c, src/nss/digests.c, src/nss/hmac.c, src/nss/signatures.c
make check-crypto-nss XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha224-rsa-sha224"
passes with this, previously it was skipped as the digest transform wasn't
implemented. Same for
aleksey-xmldsig-01/enveloping-sha224-hmac-sha224-64 and
aleksey-xmldsig-01/enveloping-sha224-hmac-sha224.
=> nss: add SHA224 support

win32/Makefile.msvc
The c compiler in vs2008 does not support inline directive.
There is no other places where this directive is used, so I just remove it instead of adding macros.
=> fix build module openssl for vs2008

configure.ac
The code uses #include <prinit.h> and #include <nss.h>, so test that in
configure as well.
I build with
```./configure --with-pic --disable-shared --disable-crypto-dl --without-libxslt --without-gnutls --enable-silent-rules --without-openssl --without-gcrypt --enable-debugging```
on Linux, which implicitly enables only NSS, and without this patch the tip of master failed for me with
```At least one crypto library should exist ...```
=> NSS: fix configure tests

configure.ac
Evaluating the condition resulted in a syntax errors, so it was always
false.
This fixes the `./configure --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --enable-mscrypto --without-openssl && make` build, which used to fail while linking.
=> configure: fix lost -lcrypt32 in mscrypto/mingw code

src/mscrypto/app.c
make check-crypto-mscrypto XMLSEC_TEST_NAME="enveloping-sha256-rsa-sha256-relationship"
when invoked from a mingw build fails here. Seems to be introduced with
the last hunk of `git show fd1807670 -- src/mscrypto/app.c`.
=> mscrypto: fix typo in xmlSecMSCryptoAppPkcs12LoadMemory()

apps/xmlsec.c, include/xmlsec/keysdata.h, src/keysdata.c, src/mscrypto/app.c, tests/testrun.sh
make check-crypto-mscrypto wants to have persistent private keys when
dealing with password-protected .p12 files, as discussed in the mailing
list thread at
<https://www.aleksey.com/pipermail/xmlsec/2017/010226.html>.
Enabling them by default would be problematic though, see commit
c098aed450a8ae272efad1fdeaa2450b67a2f46f (don't create files on
xmlsec-mscrypto when loading the key (bug #633924), 2014-05-23).
Try to please both use-cases by setting an environment variable as part
of 'make check-crypto-mscrypto', and then reacting to that in the
mscrypto backend.
=> mscrypto: work around persistence problem for the testsuite

win32/Makefile.msvc
"default" does not apply the needed --pkcs12-persist flag, "mscrypto"
does, so resolve the default at an nmake level, not inside the xmlsec
app.
(This is the last bit to get testsuite working for MSVC-built binaries, I think -- previously I ran 'make check' in a mingw tree with manually copied in MSVC-built binaries.)
=> nmake: fix testsuite invocation for the mscrypto backend

include/xmlsec/mscng/crypto.h, include/xmlsec/mscng/x509.h, src/mscng/app.c, src/mscng/certkeys.c, src/mscng/crypto.c, src/mscng/digests.c, src/mscng/globals.h, src/mscng/signatures.c, src/mscng/x509.c, src/mscng/x509vfy.c, tests/testDSig.sh, win32/Makefile.msvc
A number of commits, mostly split to allow easier reviewing. Lots of skeleton code to allow runtime testing of actual code instead of just a build test.
````
win32/binaries/xmlsec.exe check-transforms  --crypto mscng --crypto-config win32/tmp/xmlsec-crypto-config sha256 ecdsa-sha256
win32/binaries/xmlsec.exe check-key-data --crypto mscng --crypto-config win32/tmp/xmlsec-crypto-config ecdsa x509
````
Now finishes without errors, the next test is
````
win32/binaries/xmlsec.exe verify --crypto mscng --crypto-config win32/tmp/xmlsec-crypto-config --trusted-der tests/keys/cacert.der --enabled-key-data x509 tests/aleksey-xmldsig-01/enveloping-sha256-ecdsa-sha256.xml
````
that currently stops with a not-implemented-error when it comes to the cng x509 key data constructor.
Slowly getting …
=> MS CNG: adopt trusted certificate

include/xmlsec/mscng/certkeys.h, include/xmlsec/mscng/x509.h, src/mscng/certkeys.c, src/mscng/x509.c, src/mscng/x509vfy.c
The next TODO is to replace the stub at the end of xmlSecMSCngKeyDataX509VerifyAndExtractKey() with a real implementation (checks like not valid before/after, etc.)
One shortcut I did was to bypass certificate chain validation for now -- so I just report a not implemented error for that, which means that the test cmdline I use to get the above TODO is now:
````
win32/binaries/xmlsec.exe verify --crypto mscng --crypto-config win32/tmp/xmlsec-crypto-config --trusted-der tests/keys/cacert.der --enabled-key-data x509 --insecure tests/aleksey-xmldsig-01/enveloping-sha256-ecdsa-sha256.xml
````
=> MSCNG: implement public key extraction from certificate

include/xmlsec/mscng/certkeys.h, src/mscng/certkeys.c, src/mscng/signatures.c, src/mscng/x509.c
The
````
win32/binaries/xmlsec.exe verify --crypto mscng --crypto-config win32/tmp/xmlsec-crypto-config --trusted-der tests/keys/cacert.der --enabled-key-data x509 --insecure tests/aleksey-xmldsig-01/enveloping-sha256-ecdsa-sha256.xml
````
test now succeeds nicely, next TODO will be to not fail when --insecure is not used.
=> MSCNG: verify signature

src/mscng/app.c, src/mscng/certkeys.c, src/mscng/digests.c, src/mscng/signatures.c, src/mscng/x509vfy.c
````
XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha256-ecdsa-sha256" nmake check-dsig
````
now passes up to the 'Verify existing signature' part (previously this was broken as the test doesn't use the `--insecure` flag). Next TODO will be signature creation.
=> MSCNG: verify certificate

apps/xmlsec.c, src/mscrypto/app.c
MSVC 2008 and 2010 both give compilation errors when trying to compile xmlsec with mscrypto.
Like this:
..\src\mscrypto\app.c(513) : error C2275: 'DWORD' : illegal use of this type as an expression
C:\Program Files\Microsoft SDKs\Windows\v6.0A\include\windef.h(152) : see declaration of 'DWORD'
..\src\mscrypto\app.c(513) : error C2146: syntax error : missing ';' before identifier 'dwFlags'
..\src\mscrypto\app.c(513) : error C2065: 'dwFlags' : undeclared identifier
..\src\mscrypto\app.c(515) : error C2065: 'dwFlags' : undeclared identifier
..\src\mscrypto\app.c(517) : error C2065: 'dwFlags' : undeclared identifier
..\src\mscrypto\app.c(534) : error C2143: syntax error : missing ';' before 'type'
..\src\mscrypto\app.c(535) : error C2275: 'DWORD' : illegal use of this type as an expression …
=> Declare variables at the beginning of functions to fix compilation errors with MSVC

include/xmlsec/mscng/certkeys.h, include/xmlsec/mscng/crypto.h, include/xmlsec/mscng/x509.h, src/mscng/app.c, src/mscng/certkeys.c, src/mscng/crypto.c, src/mscng/signatures.c, src/mscng/x509.c, tests/testrun.sh, win32/Makefile.msvc
This implements handling of private key / key certificate. Next TODO will be xmlSecMSCngKeyDataX509XmlWrite(), i.e. XML serialization of all this.
=> MSCNG: adopt key certificate

src/mscrypto/app.c
The recent declaration-after-statement warning fix moved the initialization out
of the loop, which causes signing tests to fail. E.g.
XMLSEC_TEST_NAME="enveloping-sha256-rsa-sha256-relationship" nmake check-dsig
is a reproducer.
=> mscrypto: fix regression in xmlSecMSCryptoAppPkcs12LoadMemory()

include/xmlsec/mscng/crypto.h, src/mscng/crypto.c, src/mscng/digests.c, src/mscng/signatures.c
````
XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha1-ecdsa-sha1" nmake check-dsig
XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha512-ecdsa-sha512" nmake check-dsig
````
These two testcases now pass with the changes.
=> MSCNG: add SHA1 and SHA256 support for ECDSA

tests/README, tests/testDSig.sh, tests/testEnc.sh, tests/testKeys.sh
The motivation is that I've started adding support for RSA in the mscng
backend but I wanted to have an opt-in way to make sure I don't break
something in the existing ECDSA part.
=> tests: add support for reproducible output

apps/xmlsec.c, configure.ac
And fix the two warnings I found this way.
If this looks good, sooner or later the same would make sense for nmake as well.
=> autotools: add switch to build with -Werror

src/mscrypto/csp_calg.h
CryptAcquireContext() needs a proper crypto provider name, the one that can be found in the list of all CSPs in Windows registry: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Defaults\Provider
CryptAcquireContext failed with the previously specified provider name "CryptoPro CSP". The name for GOST 2001 provider by CryptoPro is "Crypto-Pro GOST R 34.10-2001 Cryptographic Service Provider", not just "CryptoPro CSP".
=> mscrypto: fix selection CryptoPro CSP provider for GOST R 34.10-2001

src/nss/crypto.c, src/nss/pkikeys.c
Two fixes for the ECDSA support in the NSS backend.
=> NSS: ECDSA updates

AUTHORS, include/xmlsec/mscng/app.h, include/xmlsec/mscng/certkeys.h, include/xmlsec/mscng/crypto.h, include/xmlsec/mscng/keysstore.h, include/xmlsec/mscng/symbols.h, include/xmlsec/mscng/x509.h, src/mscng/README, src/mscng/app.c, src/mscng/certkeys.c, src/mscng/crypto.c, src/mscng/digests.c, src/mscng/globals.h, src/mscng/keysstore.c, src/mscng/signatures.c, src/mscng/x509.c, src/mscng/x509vfy.c, tests/keysstore/README, tests/keysstore/keysstore.xml, win32/Makefile.msvc
I imagine the main benefit of this is hardware-based keys, where either the system provides them or we can't work with them.
=> MSCNG: add keys store support

src/openssl/x509.c, src/openssl/x509vfy.c, src/relationship.c, src/xmltree.c
Plain vanilla C allows you to return void * and assign to any pointer type.
Unfortunately I have a need to compile the source through an XCode project which for compatibility reasons is set to compile all C, C++ and Obj-C source code using Objective-C++ rules which requires void * to be explicitly cast (see issue #176)
This PR performs those casts.
=> Add explicit void* casts

src/mscng/certkeys.c, src/mscng/ciphers.c, src/mscng/signatures.c, src/xpath.c, win32/Makefile.msvc, win32/configure.js
And fix the warnings found by clang-cl in the mscng backend, one of them is gold, I think.
=> nmake: allow building with a custom C compiler

src/openssl/x509.c, src/openssl/x509vfy.c
Windows headers also #define some names that openssl uses too.
Openssl headers #undef the offending names before reusing them.
But if those offending Windows headers get included _after_ the
openssl headers the namespace gets polluted.
=> mingw64 build: move openssl header includes to the last

src/mscng/signatures.c, src/mscng/x509.c, src/xmltree.c
=> mscng: fix use-after-free

configure.ac, src/mscng/app.c, src/mscng/x509vfy.c, src/xmldsig.c, src/xmlenc.c
Seems this worked only by accident on Linux so far.
=> configure: macOS improvement

tests/oss-fuzz/README.md, tests/oss-fuzz/config/xmlsec_fuzzer.options, tests/oss-fuzz/xmlsec_target.c
This PR
- Adds one test harness to be later used by oss-fuzz
- This test harness fuzzes the `xmlSecParseMemory` API only
- Adds configuration file to be later used by oss-fuzz
=> oss-fuzz: Added one test harness and fuzzer config

.travis.yml
The intention is to catch new warnings early, rather than fixing them in
separate follow-up commits.
A local werror build works for me, let's see if it passes travis.
=> travis: enable warnings as errors

include/xmlsec/private.h, src/keysmngr.c, src/mscng/keysstore.c, win32/Makefile.msvc
`cscript configure.js crypto=mscng iconv=no static=no debug=yes werror=yes && nmake` passes for me with these, with VS2017.
=> mscng: fix cl.exe warnings

appveyor.yml, src/mscrypto/keysstore.c
And then turn on appveyor werror for that backend as well.
=> mscrypto: fix the last cl.exe warning

src/nss/x509vfy.c
As pointed out by valgrind:
==18992== 75 bytes in 1 blocks are definitely lost in loss record 47 of 69
==18992==    at 0x4C2E08F: malloc (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==18992==    by 0x5100DE1: xmlStrndup (in /usr/lib64/libxml2.so.2.9.7)
==18992==    by 0x53DAC44: xmlSecNssGetCertName (x509vfy.c:373)
==18992==    by 0x53DB08B: xmlSecNssX509FindCert (x509vfy.c:447)
==18992==    by 0x53DB08B: xmlSecNssX509StoreFindCert (x509vfy.c:147)
==18992==    by 0x53D9029: xmlSecNssX509IssuerSerialNodeRead (x509.c:1177)
==18992==    by 0x53D9029: xmlSecNssX509DataNodeRead (x509.c:918)
==18992==    by 0x53D9029: xmlSecNssKeyDataX509XmlRead (x509.c:683)
==18992==    by 0x56107FF: xmlSecKeyInfoNodeRead (keyinfo.c:112)
==18992==    by 0x5615D56: xmlSecKeysMngrGetKey …
=> nss: fix memory leak in GetCertName()

src/nss/x509.c
When building with clang -fsanitize=undefined, ubsan says:
x509.c:1750:46: runtime error: shift exponent 64 is too large for 64-bit type 'PRUint64' (aka 'unsigned long')
#0 0x444d45 in xmlSecNssASN1IntegerWrite src/nss/x509.c:1750:46
#1 0x4443ec in xmlSecNssX509IssuerSerialNodeWrite src/nss/x509.c:1259:11
#2 0x4403ba in xmlSecNssKeyDataX509XmlWrite src/nss/x509.c:769:19
#3 0x45962a in xmlSecKeyInfoNodeWrite src/keyinfo.c:180:19
#4 0x480149 in xmlSecDSigCtxProcessKeyInfoNode src/xmldsig.c:807:15
#5 0x47c774 in xmlSecDSigCtxProcessSignatureNode src/xmldsig.c:506:11
#6 0x47bfb2 in xmlSecDSigCtxSign src/xmldsig.c:289:11
And indeed shifting a 64bit value by 64 bits happens in practice there
as num->len is 9. At the same time (at least in case of the test) in all
3 cases the value that would be …
=> nss: fix undefined behavior due to too large shift

src/nss/x509.c
The intention is that either we have data which can be represented with
a 64bit unsigned integer, or if the data is larger than that, then it's
just leading zeros one can ignore.
=> nss: improve assert in xmlSecNssASN1IntegerWrite()

win32/Makefile.msvc, win32/configure.js
Use-case is e.g. wanting to build the code with -arch:SSE. And this improves
consistency, autotools allows custom compiler flags as well.
=> win32: allow custom compiler flags

configure.ac
When xmlsec is configured to build a static library, and the build is configured to use a static openssl library, the build fails on macOS (Xcode 10, macOS 10.14) while linking the `xmlsec` library:
```
ld: warning: ignoring file ../src/openssl/.libs/libxmlsec1-openssl.a, file was built for archive which is not the architecture being linked (x86_64): ../src/openssl/.libs/libxmlsec1-openssl.a
Undefined symbols for architecture x86_64:
"_xmlSecOpenSSLAppDefaultKeysMngrAdoptKey", referenced from:
_xmlSecAppCryptoSimpleKeysMngrKeyAndCertsLoad in crypto.o
_xmlSecAppCryptoSimpleKeysMngrPkcs12KeyLoad in crypto.o
_xmlSecAppCryptoSimpleKeysMngrBinaryKeyLoad in crypto.o
_xmlSecAppCryptoSimpleKeysMngrKeyGenerate in crypto.o
"_xmlSecOpenSSLAppDefaultKeysMngrInit", referenced from: …
```
=> Fix errors building a static xmlsec library with a static openssl

src/openssl/evp.c
The motivation is that if ((...)) is usually used for a condition with side effects, and if that's not the case, if (...) should be used.
=> openssl: fix gcc7 -Werror,-Wparentheses-equality

src/bn.c, src/dl.c, src/io.c, src/keysdata.c, src/list.c
I think the shared code (not specific to backends) is now clean.
=> Fix some non-matching function names in xmlSecError() calls

src/bn.c, src/dl.c, src/io.c, src/keysdata.c, src/list.c, src/mscng/certkeys.c
Also re-request pulling some of the previous error handling fixes, as (I guess by accident) commit a181a96b5f73a4ac27be2fc51644326c2b89fe4d reverted these (see e.g. the changes to src/bn.c).
=> mscng: implement dsa ecdsa key size

.travis.yml, autogen.sh, docs/Makefile.am, docs/api/Makefile.am, scripts/travis-env.sh
Only the nss backend as a start.
Also, 'cp -u' is not handled by macOS, so just act similar to the
in-tree build for now.
=> CI: add initial macOS coverage

Copyright
Feel free to tweak the copyright notice section -- I just took what is used in src/mscng/ .c files, but naturally I have no problems with adding your name to the list or anything.
(Noticed this while we did a systematic update of the LibreOffice license file, noticed that this file covers the nss backend but not the mscrypto one -- we don't use the other backends.)
=> Copyright: add an mscng section

Copyright
The copyright notice and later wording referred to different names, resolve this.
=> Copyright: extend copyright notices for xmlsec-mscng

src/gnutls/x509vfy.c, tests/testrun.sh
This is required for gnutls-3.6.x.
Allow tests to use no strict checks until all certificates will be converted
to stronger signature than SHA-1.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>
=> gnutls: allow SHA-1 signed certificate when not in strict checks (#250)

apps/xmlsec.c, tests/testDSig.sh, tests/testrun.sh
The --X509-skip-strict-checks parameter is not accepted by all commands,
result of skipping many tests.
Reduce impact of the --X509-skip-strict-checks to a workaround to gnutls only.
Filter double --X509-skip-strict-checks commands as cli does not accept
multiple instances.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>
=> tests: workout test --X509-skip-strict-checks

configure.ac
The change in this pull request is based on a patch in the pkgsrc repository that is required in order to compile xmlsec in other OSs supported by pkgsrc.
Currently pkgsrc is using xmlsec1 1.2.25.  Merging this pull request would make it simpler to upgrade the xmlsec version shipped with pkgsrc.
See also https://github.com/NetBSD/pkgsrc/blob/pkgsrc-2018Q4/security/xmlsec1/patches/patch-ab#L39
=> Add configure support for further OS's

include/xmlsec/gnutls/crypto.h
If xmlsec1 is configured like below
./configure --disable-dsa --disable-rsa
then it fails to build reporting that GNUTLS_E_SUCCESS is undefined.
=> Fix undefined GNUTLS_E_SUCCESS

src/xmldsig.c
The userData pointer that upper layers using xmlsec could set to a xmlSecDSigCtx structure, before calling any xmldsig related function, is not available while executing referencePreExecuteCallback function. This change will allow upper layers to use that userData pointer, if desired, to pass some info which might be helpful for them while validating/changing the transform chain.
=> Make userData pointer available in referencePreExecuteCallback function when using xmldsig ctx

src/dl.c
In an Universal Windows Platform app it is not allowed to LoadLibrary a classic desktop library, we have to use LoadPackagedLibrary instead.
=> Allow compilation on UWP

src/openssl/crypto.c
In our unit test scenario the xmlsec library is unloaded every time, while OpenSSL is held. Sometimes this leads to an exception in OpenSSL ERR_load_strings call. Fixed by calling ERR_unload_strings.
=> Unload error strings in OpenSSL shutdown.

src/openssl/app.c
Hello,
In OpenSSL, PKCS12_parse returns 0 in case of error. This commit properly handle the error case.
Note: it is not a severe error since if an error occurs when parsing the pkcs12 keystore, the call to xmlSecOpenSSLEvpKeyAdopt will immediatly fail. But it will not report the real root cause in the logs.
It will report:
```
func=xmlSecOpenSSLEvpKeyAdopt:file=evp.c:line=351:obj=unknown:subj=pKey != NULL:error=100:assertion:
```
With the fix, we will have the following line in the logs:
```
func=xmlSecOpenSSLAppPkcs12LoadBIO:file=app.c:line=633:obj=unknown:subj=PKCS12_parse:error=4:crypto library function failed:openssl error: 50856204: digital envelope routines: NULL unsupported
```
Regards,
=> Fix PKCS12_parse return code handling

configure.ac
Hello,
The validation of OpenSSL presence is done by the following program:
```c
#include <openssl/opensslv.h>
int main () {
#if OPENSSL_VERSION_NUMBER < 0x10100000L
SSL_library_init();
#else
OPENSSL_init_ssl(0, NULL);
#endif
return(0);
}
```
But the function OPENSSL_init_ssl is not declared in this header but in
ssl.h.
This lead to the following error:
```
/home/docker/testconf_xmlsec.c: In function 'main':                                                                                                                                                                                                                            /home/docker/testconf_xmlsec.c:57:17: warning: implicit declaration of function 'OPENSSL_init_ssl' [-Wimplicit-function-declaration]
OPENSSL_init_ssl(0, NULL); …
```
=> Fix OpenSSL lookup

src/x509.c
LibreOffice wants to write the content of KeyInfo itself and thus writes
X509Certificate element with content.
But then xmlSecMSCngKeyDataX509XmlWrite() writes a duplicate
X509Certificate element, which then makes a new additional consistency
check in LO unhappy.
The duplicate is written because xmlSecX509DataGetNodeContent() returns
0 because it only checks for empty nodes; if there are only non-empty
nodes a fallback to XMLSEC_X509DATA_DEFAULT occurs in all backends.
Change the return value to be non-0 without changing the signature of
the function, as it is apparently public.
This doesn't happen in LO in the NSS backend due to another accident,
where the private key flag isn't set when the X509Certificate is read,
but otherwise the code is the same.
=> xmlSecX509DataGetNodeContent(): don't return 0 for non-empty elements

configure.ac
This fixes mscrypto and mscng detection with clang mingw toolchain.
AC_LANG_PROGRAM implicitly adds main function in test source file.
Without this change, the test source file has two nested main functions.
https://www.gnu.org/software/autoconf/manual/html_node/Generating-Sources.html
=> configure: Fix mscrypto and mscng tests

configure.ac
See reasons: https://github.com/lsh123/xmlsec/discussions/410
=> reduce nss/nspr lib versions

examples/xmldsigverify.c
this ensures that xmlSecParserSetDefaultOptions definition is made available
Fixes
| xmldsigverify.c:275:5: error: call to undeclared function 'xmlSecParserSetDefaultOptions'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
|     xmlSecParserSetDefaultOptions(XML_PARSE_NOENT | XML_PARSE_NOCDATA |
|     ^
Signed-off-by: Khem Raj <raj.khem@gmail.com>
=> xmldsigverify: Include xmlsec/parser.h

Makefile.am, configure.ac
=> Ensure 'make check' works correctly when dynamic crypto loading is disabled

src/gnutls/Makefile.am
=> ensure linking against GCrypt libraries for xmlsec-gnutls

src/gnutls/app.c, src/mscng/app.c, src/mscrypto/app.c, src/nss/app.c, src/openssl/app.c
=> Fix x509data->keyCert when loading a key from a cert

src/mscng/x509vfy.c, src/mscrypto/x509vfy.c
If certificate is revoked then we should free CRL context explicitly because CertEnumCRLsInStore in this function will not be called again.
Part of #638.
=> xmlsec-mscrypto/mscng: fix CRL_CONTEXT leak

src/mscng/x509.c, src/mscrypto/x509.c
*AdoptCert fuctions do free contexts on success while *AdoptCrl functions don't. If we check calls to both *AdoptCert and *AdoptCrl we'll see that high-level code always expects that contexts will not be freed on error and will be freed on success.
=> xmlsec-mscrypto/mscng: fix leaks in *AdoptCrl functions for WinAPI

src/mscrypto/x509.c
xmlSecMSCryptoKeyDataX509GetCrl creates CRL contexts, so they should be freed one way or another.
Looks like CNG counterpart of this patch does not exist. I don't see similar problems there. Presumably this is a positive side effect of refactoring: someone removed old certificate/CRL traversing code with O(n^2) complexity.
=> xmlsec-mscrypto: fix CRL_CONTEXT leaks

src/mscng/x509.c, src/mscng/x509vfy.c, src/mscrypto/x509.c, src/mscrypto/x509vfy.c
Make behavior consistent with similar functions *AdoptCert and *AdoptCrl and with high-level calls from two instances of app.c.
Similar to https://github.com/lsh123/xmlsec/pull/641.
=> xmlsec-mscrypto/mscng: fix leaks in *StoreAdoptCert, fix CERT_CONTEXT leaks

src/mscng/x509.c
srcCert isn't freed on error.
CNG counterpart of https://github.com/lsh123/xmlsec/pull/643.
=> xmlsec-mscng: fix CERT_CONTEXT leaks

src/mscrypto/x509.c
xmlSecMSCryptoKeyDataX509GetCert creates certificate contexts, so they should be freed one way or another.
CNG counterpart of this patch will follow as a separate merge request if I will find any leaks.
=> xmlsec-mscrypto: fix CERT_CONTEXT leaks

src/mscng/app.c, src/mscrypto/app.c, src/mscrypto/keysstore.c, src/mscrypto/x509.c
Some contexts are not freed on errors.
=> xmlsec-mscrypto/mscng: fix CERT_CONTEXT leaks

src/mscrypto/x509.c, src/mscrypto/x509vfy.c
As far as I can see, after all previous commits there should be no leaks regarding ctx->trusted, ctx->untrusted, ctx->hMemStore. CERT_CLOSE_STORE_FORCE_FLAG becomes useless so it's better to remove it because documentation advices against it's usage.
=> xmlsec-mscrypto: remove CERT_CLOSE_STORE_FORCE_FLAG

src/openssl/openssl_compat.h
LibreSSL added `UI_null()` in 3.7.1.
There are still issues with the current commit (https://github.com/lsh123/xmlsec/commit/4c7500252f20170f379081abccb750f0840407f4), but that is less obvious to resolve and I will try to follow up later.
=> openssl_compat.h: Update LibreSSL UI_null() compat

configure.ac
Hi again! This is a follow-up for yesterday's https://github.com/lsh123/xmlsec/pull/661.
The 'Just try to compile/link and hope for the best' failed for me because the program used a function from `libssl`, but didn't link to it. The immediate workaround was to set `OPENSSL_LIBS="-lcrypto -lssl"`, but I don't think this is a good workaround -- it also links the main libraries/programs to `libssl`.
I think configure can test initialization from `libcrypto` instead. The call works fine for both 1.1.1 and 3.x, at least from what I tested.
=> configure: Switch to OPENSSL_init_crypto in test program

configure.ac, include/xmlsec/exports.h
=> Force static linking for libraries when --enable-static-linking is specified on Windows (MinGW/Cygwin)

apps/xmlsec.c, docs/index.html
Also see https://github.com/lsh123/xmlsec/discussions/705
=> (xmlsec command line tool) Added  option to control the base64 encoding line size.

win32/Makefile.msvc
Hi, I know that branch 1.2.x is legacy, but I still hope that you'll accept this fix and release a new version.
=> fix openssl engine headers install on windows

include/xmlsec/app.h
Fixed typo introduced by https://github.com/lsh123/xmlsec/commit/aa98f933293b592421bf968c6bff74b1e1eff102
=> Fix typo with xmlSecKeyDataEcGetKlass in app.h include

configure.ac
When building with LibreSSL or BoringSSL the build will try to link the `$OPENSSL_LIBS` with `-Wl,-Bstatic`, but this will fail when using slibtool if only dynamic libssl and libcrypto libraries are installed.
```
ld: cannot find -lssl: No such file or directory
ld: cannot find -lcrypto: No such file or directory
```
With GNU libtool it will "helpfully" rearrange the linker output to obscure the issue.
```
-lssl -lcrypto -lxslt -lxml2 ../.libs/libxmlsec1.so -g -O2 -O -Wl,-Bstatic -Wl,-Bdynamic
```
While with slibtool it will do as instructed and produce a build failure.
```
-Wl,-Bstatic -lssl -lcrypto -Wl,-Bdynamic -lxslt
```
=> configure.ac: fix the build with slibtool

src/gcrypt/asymkeys.c
=> (xmlsec-gcrypt) Fix memory leak in xmlSecGCryptAsymKeyDataAdoptKey

tests/testDSig.sh, tests/testEnc.sh, tests/testKeys.sh, tests/testRes.sh, tests/testrun.sh
=> (xmlsec-tests) Ensure tests can run with -jN

src/gcrypt/asymkeys.c
The issue was introduced in PR #790; also see PR #794
=> (xmlsec-gcrypt) Fix double free in xmlSecGCryptAsymKeyDataGenerate

src/openssl/app.c, src/openssl/crypto.c
=> (xmlsec-openssl) Fix memory leak if file doesn't exist

include/xmlsec/keysdata.h, include/xmlsec/keysmngr.h, include/xmlsec/list.h, include/xmlsec/transforms.h, src/kw_aes_des.h
=> (xmlsec-core) Remove 'const struct' to avoid problems with some compilers

include/xmlsec/keysdata.h, include/xmlsec/keysmngr.h, include/xmlsec/list.h, include/xmlsec/transforms.h, src/kw_aes_des.h
=> Revert "(xmlsec-core) Remove 'const struct' to avoid problems with some compilers"

src/openssl/app.c
xmlsec can't be compiled on systems where openss/engine.h is missing. In some distributions this file is in extra package (Fedora) or not present at all.
This update makes the include conditional based on `configure` option `--enable_openssl3_engines`.
=> Conditional include for openssl engines

docs/index.html, src/mscng/x509vfy.c, tests/testDSig.sh
=> (xmlsec-mscng) Added an option to skip timestamp checks for certificates and CLRs

include/xmlsec/transforms.h
Otherwise gcc-12 breaks with:
In file included from ../include/xmlsec/keyinfo.h:24:0,
from ../include/xmlsec/keysmngr.h:19,
from ../include/xmlsec/app.h:26,
from app.c:30:
../include/xmlsec/transforms.h:449:5: error: unknown type name ‘uintptr_t’
uintptr_t                           flags;
^~~~~~~~~
=> transforms: add missing include

src/openssl/openssl_compat.h, src/openssl/signatures_legacy.c
All these functions return an int in openssl, and a size_t into aws-lc.
=> Build fix for aws-lc for functions returning size_t

src/openssl/signatures.c
Avoid such a warning when building with XMLSEC_NO_DSA or XMLSEC_NO_EC:
CC       libxmlsec1_openssl_la-signatures.lo
../../../src/openssl/signatures.c: In function 'xmlSecOpenSSLEvpSignatureVerify':
../../../src/openssl/signatures.c:985:9: warning: unused variable 'fixedDataLen' [-Wunused-variable]
985 |     int fixedDataLen = 0;
=> Fix warnings from xmlSecOpenSSLEvpSignatureVerify()

src/openssl/x509vfy.c
Prevent these warnings about unused parameter when building with XMLSEC_OPENSSL_NO_CRL_VERIFICATION. This is the case with aws-lc.
../../../src/openssl/x509vfy.c: In function 'xmlSecOpenSSLX509VerifyCRL': ../../../src/openssl/x509vfy.c:1271:40: warning: unused parameter 'xst' [-Wunused-parameter] 1271 | xmlSecOpenSSLX509VerifyCRL(X509_STORE* xst, X509_STORE_CTX* xsc, STACK_OF(X509)* untrusted, X509_CRL crl, xmlSecKeyInfoCtx keyInfoCtx) { | ~~~~~~~~~~~~^~~
../../../src/openssl/x509vfy.c:1271:61: warning: unused parameter 'xsc' [-Wunused-parameter] 1271 | xmlSecOpenSSLX509VerifyCRL(X509_STORE* xst, X509_STORE_CTX* xsc, STACK_OF(X509)* untrusted, X509_CRL crl, xmlSecKeyInfoCtx keyInfoCtx) { | ~~~~~~~~~~~~~~~~^~~
../../../src/openssl/x509vfy.c:1271:82: warning: unused parameter 'untrusted' …
=> Fix xmlSecOpenSSLX509VerifyCRL() unused parameters

src/openssl/openssl_compat.h
All these functions take a size_t as parameter in aws-lc/boringssl API in place of an int in OpenSSL API. This is safe to cast int to size_t for value which are not supposed to be negative (lengths or number of bits here).
This patch fixes these warnings:
../../../src/openssl/evp.c: In function 'xmlSecOpenSSLGetBNValue':
../../../src/openssl/evp.c:58:35: warning: conversion to 'size_t' {aka 'long unsigned in t'} from 'int' may change the sign of the result [-Wsign-conversion]
58 |     (*bigNum) = BN_bin2bn(bufPtr, bufLen, (*bigNum));
|                                   ^~~~~~
CC       libxmlsec1_openssl_la-kdf.lo
CC       libxmlsec1_openssl_la-key_agrmnt.lo
CC       libxmlsec1_openssl_la-keysstore.lo
CC       libxmlsec1_openssl_la-hmac.lo
../../../src/openssl/hmac.c: In function …
=> Fix function prototypes with a size_t parameter

src/openssl/app.c, src/openssl/ciphers.c, src/openssl/globals.h, src/openssl/openssl_compat.h, src/openssl/x509.c, src/openssl/x509vfy.c
@haproxyFred the original patches broke BoringSSL build. I also feel this is a bit more readable. The remaining casts could be done the same way too (I will do it in another patch). This builds cleanly for me on OpenSSL/BoringSSL/AWS-LC. Can you check that this works for you too?
=> Fix build for AWS-LC and BoringSSL

include/xmlsec/templates.h, src/templates.c
Just 2 template API additions i found useful you might be interested in.
=> Add RSA MGF1 and digest template API

configure.ac, include/xmlsec/openssl/crypto.h, src/openssl/app.c, src/openssl/crypto.c, src/openssl/openssl_compat.h, src/openssl/x509.c
This PR explicitly ifdef's xmlsec code with the macro OPENSSL_IS_AWSLC as discussed in issue #908
=> (xmlsec-openssl) Fix AWS-LC support
