lsh123/xmlsec

- apps/xmlsec.c
- configure.ac
- examples/sign3.c
- include/xmlsec/xmltree.h
- src/gnutls/x509.c
- src/mscrypto/x509.c
- src/nss/x509.c
- src/openssl/x509.c
- src/x509.c
- src/xmltree.c
> Fix x509data templ

- Makefile.am
- tests/testDSig.sh
- tests/testEnc.sh
- tests/testKeys.sh
See [ltdl documentation](https://www.gnu.org/software/libtool/manual/html_node/Libltdl-interface.html#Libltdl-interface).
This should work on *nix/mingw32/mingw64
> make check: replace LD_LIBRARY_PATH with LTDL_LIBRARY_PATH

- include/xmlsec/mscng/certkeys.h
- include/xmlsec/mscng/x509.h
- src/mscng/app.c
- src/mscng/certkeys.c
- src/mscng/signatures.c
- src/mscng/x509.c
````
XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha256-ecdsa-sha256" nmake check-dsig
````
finally passes completely. :-)
Next TODO is other hashing algorithms I guess, like sha1 and sha512 for ecdsa.
> mscng: signature creation

- include/xmlsec/mscng/crypto.h
- src/mscng/certkeys.c
- src/mscng/crypto.c
- src/mscng/digests.c
- src/mscng/signatures.c
RSA with a couple of hashing variants (SHA384 is entirely new).
> MSCNG: add RSA support

- examples/verify3.c
Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
> xmlsec1: fix a typo in examples/verify3.c

- include/xmlsec/mscng/crypto.h
- src/mscng/certkeys.c
- src/mscng/crypto.c
- src/mscng/digests.c
- src/mscng/signatures.c
> MSCNG: add DSA support

- include/xmlsec/mscng/crypto.h
- include/xmlsec/mscng/x509.h
- src/mscng/crypto.c
- src/mscng/x509.c
- src/mscng/x509vfy.c
And other necessary improvements to get the mentioned testcase pass.
> MSCNG: handle --verification-time

- include/xmlsec/mscng/certkeys.h
- src/mscng/app.c
- src/mscng/digests.c
- src/mscng/signatures.c
- src/mscng/x509.c
- win32/Makefile.msvc
- win32/configure.js
> Nmake werror

- src/mscng/certkeys.c
Support DSA keys which are not inside x509 certs.
> MSCNG: raw DSA support

- include/xmlsec/mscng/crypto.h
- src/mscng/crypto.c
- src/mscng/globals.h
- src/mscng/x509.c
- src/mscng/x509vfy.c
And two more commits, so 2 more testcases now pass.
> MSCNG: adopt untrusted cert

- src/openssl/x509.c
Fixed issue #164. All other crypto libraries are ok.
> Add missing return(-1).

- include/xmlsec/mscng/crypto.h
- include/xmlsec/mscng/x509.h
- src/mscng/certkeys.c
- src/mscng/crypto.c
- src/mscng/symkeys.c
- src/mscng/x509.c
And a couple related smaller things. I think the dsig support in the mscng backend starts to look reasonable with this.
> MSCNG: add raw RSA support

- include/xmlsec/mscng/crypto.h
- src/mscng/certkeys.c
- src/mscng/ciphers.c
- src/mscng/crypto.c
- src/mscng/kt_rsa.c
- src/mscng/symkeys.c
- src/mscng/x509vfy.c
- win32/Makefile.msvc
Just rsa-1_5 / aes256-cbc as a start.
> MSCNG: add initial decrypt support

- configure.ac
- include/xmlsec/openssl/crypto.h
- src/openssl/openssl_compat.h
Implement @lsh123's comments for #159
Signed-off-by: Bernard Spil <brnrd@FreeBSD.org>
> Fix build with LibreSSL 2.7

- include/xmlsec/mscng/crypto.h
- src/mscng/certkeys.c
- src/mscng/ciphers.c
- src/mscng/crypto.c
- src/mscng/kt_rsa.c
- src/mscng/symkeys.c
The key transport variants are handled, key wrapper ones are still missing.
> MSCNG: initial encrypt support

- configure.ac
- include/xmlsec/crypto.h
- include/xmlsec/mscng/Makefile.am
- include/xmlsec/mscng/app.h
- src/base64.c
- src/mscng/Makefile.am
And fix the single issue it found, a missing include.
> MSCNG: add automake integration for mingw

- src/mscng/app.c
- src/mscng/x509vfy.c
Fix the two issues showed up as part of make check since it started to actually exit with an error on failure.
> MSCNG: ci fixes

- include/xmlsec/nss/crypto.h
- src/mscng/app.c
- src/nss/crypto.c
- src/nss/signatures.c
- src/templates.c
Also 2 more changes that were already waiting in my tree.
> nss: add dsa sha256 support

- include/xmlsec/mscng/crypto.h
- src/mscng/crypto.c
- src/mscng/signatures.c
Testcase: XMLSEC_TEST_NAME="aleksey-xmldsig-01/enveloping-sha384-ecdsa-sha384" nmake check-dsig
> mscng: add ECDSA-SHA384 support

- appveyor.yml
This works for me locally, so start with that as a first step.
> appveyor: enable werror for the mscng backend

- src/bn.c
- src/nss/signatures.c
- src/nss/x509vfy.c
As HACKING recommends.
Fix violations in shared code + nss backend.
> readability: put braces around some statements

- docs/Makefile.am
- src/gnutls/x509.c
- src/openssl/x509vfy.c
- src/xslt.c
In gnutls, openssl and xslt code which I forgot to include last time.
> Remaining braces-around-statements fixes

- .travis.yml
- scripts/travis-env.sh
- tests/testEnc.sh
Which allows testing the openssl bacheck as part of CI.
> tests: fix base64 invocation on macOS

- tests/testrun.sh
> tests: use --X509-skip-strict-checks only for verify

- configure.ac
Based on https://github.com/lsh123/xmlsec/pull/297
> Add an option to use secure memset

- apps/crypto.c
- apps/crypto.h
- apps/xmlsec.c
- appveyor.yml
- include/xmlsec/keysdata.h
- include/xmlsec/openssl/app.h
- src/openssl/app.c
Based on https://github.com/lsh123/xmlsec/pull/322
> Added --privkey-openssl-engine option to enhance openssl engine support

- include/xmlsec/xmltree.h
- src/cast_helpers.h
- src/dl.c
- src/nss/app.c
- src/nss/bignum.c
- src/nss/ciphers.c
- src/nss/crypto.c
- src/nss/hmac.c
- src/nss/keytrans.c
- src/nss/kw_aes.c
- src/nss/kw_des.c
- src/nss/pkikeys.c
- src/nss/signatures.c
- src/nss/x509.c
- src/nss/x509vfy.c
- src/openssl/hmac.c
- src/xmltree.c
> fixing warning in xmlsec-nss

- src/cast_helpers.h
- src/gcrypt/asn1.c
- src/gcrypt/asymkeys.c
- src/gcrypt/ciphers.c
- src/gcrypt/hmac.c
- src/gcrypt/kw_aes.c
- src/gcrypt/kw_des.c
- src/gcrypt/signatures.c
> fix warnings in xmlsec-gcrypt

- apps/xmlsec.c
- src/gnutls/asymkeys.c
- src/gnutls/x509utils.c
- src/gnutls/x509vfy.c
> fix warning in xmlsec-gnutls

- .github/workflows/make-check.yml
- apps/crypto.c
- include/xmlsec/xmltree.h
- src/base64.c
- src/nss/x509.c
- src/nss/x509vfy.c
- src/openssl/app.c
- src/openssl/crypto.c
- src/openssl/evp.c
- src/openssl/hmac.c
- src/openssl/kt_rsa.c
- src/openssl/kw_aes.c
- src/openssl/kw_des.c
- src/openssl/signatures.c
- src/xmltree.c
> enable pedantic flags on github CI

- .github/workflows/make-check.yml
- apps/xmlsec.c
- configure.ac
- src/dl.c
- src/mscng/ciphers.c
- src/mscng/hmac.c
- src/mscng/x509vfy.c
- src/nodeset.c
- src/transforms.c
- src/xpath.c
> fix a few warnings and re-enable -werror for macosx

- .github/workflows/make-check.yml
- appveyor.yml
- tests/testrun.sh
- win32/Makefile.msvc
- win32/configure.js
- win32/mycfg.bat
> fail if no tests succeeded

- apps/cmdline.c
- apps/cmdline.h
- apps/xmlsec.c
- tests/testDSig.sh
> add verification-gmt-time to xmlsec app and switch tests to use it

- src/gcrypt/app.c
> ignore error allocating secure memory

- docs/api/xmlsec-app.html
- docs/api/xmlsec-buffer.html
- docs/api/xmlsec-index.html
- docs/api/xmlsec-mscng-crypto.html
- docs/api/xmlsec-mscrypto-crypto.html
- docs/api/xmlsec-openssl-crypto.html
- docs/api/xmlsec.devhelp2
> update docs for rsa-oaep mgf1

- configure.ac
- include/xmlsec/nss/crypto.h
- include/xmlsec/nss/symbols.h
- src/nss/crypto.c
- src/nss/keytrans.c
> add NSS RSA OAEP support

- docs/api/xmlsec-index.html
- docs/api/xmlsec-nss-crypto.html
- docs/api/xmlsec.devhelp2
- docs/index.html
- docs/news.html
- docs/xmlenc.html
- src/nss/README.md
> update docs for RSA OAEP support in xmlsec-nss

- docs/xmldsig.html
- docs/xmlenc.html
- src/nss/README.md
issue #1 (RSA PCKS 1.5 in NSS)
> updated docs to reflect deprecated algorithms

- apps/xmlsec.c
- docs/index.html
- docs/news.html
To support multiple input files (also see #461)
> Enable templatized output filename

- docs/index.html
- docs/news.html
- docs/xmldsig.html
- include/xmlsec/mscng/crypto.h
- src/mscng/crypto.c
- src/mscng/signatures.c
> Support RSA PSS SHA* for xmlsec-mscng

- docs/index.html
- docs/news.html
- docs/xmldsig.html
- include/xmlsec/gcrypt/crypto.h
- include/xmlsec/gcrypt/symbols.h
- include/xmlsec/gnutls/crypto.h
- scripts/build_memcheck.sh
- src/gcrypt/crypto.c
- src/gcrypt/signatures.c
- src/gnutls/crypto.c
- src/gnutls/signatures.c
- tests/valgrind-gcrypt.supp
> Implement RSA-PSS-SHA* for xmlsec-gcrypt and xmlsec-gnutls

- tests/README.md
- tests/testrun.sh
> Fail tests on low success rate

- include/xmlsec/gnutls/crypto.h
- src/gnutls/app.c
- src/gnutls/asymkeys.c
- src/gnutls/globals.h
> Enable reading PEM/DER keys for GnuTLS

- docs/index.html
- docs/news.html
- docs/xmldsig.html
- include/xmlsec/gnutls/crypto.h
- include/xmlsec/gnutls/symbols.h
- src/gnutls/crypto.c
- src/gnutls/signatures.c
- src/openssl/signatures.c
> Implement the DSA-SHA256 signatures for GnuTLS and fix it for OpenSSL

- src/strings.c
- tests/aleksey-xmldsig-01/enveloped-ripemd160-ecdsa-ripemd160.tmpl
- tests/aleksey-xmldsig-01/enveloped-ripemd160-ecdsa-ripemd160.xml
- tests/testDSig.sh
> Fix ecdsa-ripemd160 href

- apps/xmlsec.c
- docs/index.html
- docs/news.html
- include/xmlsec/xmldsig.h
- src/xmldsig.c
- tests/testrun.sh
> Added failure reason to xmlSecDSigCtx and --verbose option to the xmlsec command line utility

- src/nss/crypto.c
> Fix prototype

- .github/workflows/make-check.yml
- src/openssl/signatures.c
> xmlsec-openssl: fix GOST 

- examples/Makefile
- examples/verify1.c
- examples/verify2.c
> Fix examples

- configure.ac
> Detect clang to set compiler flags correctly

- configure.ac
Hi! This is same as https://github.com/lsh123/xmlsec/pull/327, but for all other third-parties.
> configure: Fix AC_LANG_PROGRAM macro usage

- configure.ac
- src/nss/ciphers_gcm.c
- src/nss/keytrans.c
See https://github.com/lsh123/xmlsec/discussions/659
> Restore support for NSS 3.35 or above

- include/xmlsec/openssl/evp.h
- src/openssl/evp.c
> Use OpenSSL functions to get key size

- .github/workflows/make-check.yml
See:
https://github.com/actions/runner-images/issues/7855
https://github.com/Homebrew/homebrew-cask/issues/150323
> Workaround broken 'brew update'

- configure.ac
> Early error in configure if libltdl is missing

- .github/workflows/make-check.yml
- configure.ac
- docs/index.html
- docs/xmldsig.html
- include/xmlsec/gnutls/crypto.h
- include/xmlsec/openssl/crypto.h
- src/gnutls/asymkeys.c
- src/gnutls/crypto.c
- src/gnutls/digests.c
- src/gnutls/signatures.c
- src/openssl/crypto.c
- src/openssl/signatures.c
- tests/aleksey-xmldsig-01/enveloped-gost2012-256.tmpl
- tests/aleksey-xmldsig-01/enveloped-gost2012-256.xml
- tests/aleksey-xmldsig-01/enveloped-gost2012-512.tmpl
- tests/aleksey-xmldsig-01/enveloped-gost2012-512.xml
And also fixed padding in xmlsec-openssl GOST support.
See issue #582
> (xmlsec-gnutls) Added support for GOST 2012

- docs/download.html
- docs/index.html
- src/nss/app.c
- src/nss/private.h
- src/nss/x509.c
- tests/testrun.sh
> (xmlsec-nss) Added support for reading PEM certificates

- docs/index.html
- src/gnutls/app.c
- src/gnutls/asymkeys.c
- src/gnutls/private.h
- src/nss/app.c
> (xmlsec-gnutls) Added a check to ensure that the key certificat matches the key.

- docs/download.html
- docs/index.html
- src/gnutls/app.c
- src/gnutls/private.h
- src/gnutls/x509.c
- src/gnutls/x509vfy.c
- src/openssl/x509vfy.c
- tests/testDSig.sh
> (xmlsec-gnutls) Added support for xmlsec command line tool '--verify-keys' option

- docs/index.html
- src/gnutls/x509vfy.c
- src/nss/app.c
- src/nss/private.h
- src/nss/x509.c
- src/nss/x509vfy.c
- tests/testDSig.sh
> (xmlsec-nss) Added support for xmlsec command line tool '--verify-keys' option.

- docs/index.html
- include/xmlsec/mscng/x509.h
- src/mscng/app.c
- src/mscng/private.h
- src/mscng/x509.c
- src/mscng/x509vfy.c
- tests/testDSig.sh
> (xmlsec-mscng) Added support for xmlsec command line tool '--verify-keys' option

- docs/download.html
> Add fingerprint for signatures to downloads page

- tests/testDSig.sh
- tests/testEnc.sh
- tests/testKeys.sh
> Add foolproof protections to ensure test scripts are not used standalone

- configure.ac
- docs/index.html
- include/xmlsec/openssl/crypto.h
- src/openssl/README.md
- src/openssl/app.c
- src/openssl/crypto.c
- src/openssl/evp.c
- src/openssl/kt_rsa.c
- src/openssl/openssl_compat.h
- src/openssl/signatures_legacy.c
- src/openssl/x509vfy.c
- tests/testrun.sh
> (xmlsec-openssl) Removed support for OpenSSL 1.1.0

- docs/index.html
- docs/xmldsig.html
- include/xmlsec/crypto.h
- include/xmlsec/keysdata.h
- src/dl.c
- src/keyinfo.c
- src/keys.c
- src/keysdata.c
- src/keysmngr.c
- tests/testDSig.sh
- tests/testEnc.sh
> (xmlsec-core) Disabled KeyValue and DEREncodedKeyValue data by default

- apps/crypto.c
- apps/xmlsec.c
- include/xmlsec/xmlsec.h
- src/errors_helpers.h
- src/mscrypto/certkeys.c
- src/mscrypto/signatures.c
> Fix libxml2 v2.12.0 includes 

- .github/workflows/make-check.yml
- configure.ac
- docs/index.html
- src/nss/crypto.c
> (xmlsec-nss) Added runtime check for the enabled algorithms in NSS (issue #730)

- src/nss/crypto.c
See https://github.com/lsh123/xmlsec/discussions/750
> (xmlsec-nss) Ensure NSS algorithms are initialized

- src/openssl/private.h
- src/openssl/x509.c
- src/openssl/x509vfy.c
> (xmlsec-openssl) Support cert dates at or before unix epoch start

- examples/decrypt1.c
- examples/decrypt2.c
- examples/decrypt3.c
- examples/encrypt1.c
- examples/encrypt2.c
- examples/encrypt3.c
- examples/sign1.c
- examples/sign2.c
- examples/sign3.c
- examples/verify1.c
- examples/verify2.c
- examples/verify3.c
- examples/verify4.c
- src/keysmngr.c
- src/templates.c
> (xmlsec-core) Replace old LibXML2 functions with newer versions

- docs/index.html
- docs/news.html
- src/openssl/ciphers.c
- src/openssl/digests.c
- src/openssl/evp.c
- src/openssl/hmac.c
- src/openssl/kt_rsa.c
- src/openssl/kw_aes.c
- src/openssl/kw_des.c
- src/openssl/openssl_compat.h
- src/openssl/signatures.c
- src/openssl/signatures_legacy.c
- src/openssl/x509.c
> Fix build for AWS-LC and BoringSSL (part 2)

- tests/testDSig.sh
- tests/testrun.sh
> (xmlsec-tests) Fix tests for AWS-LC

- include/xmlsec/app.h
- include/xmlsec/gcrypt/symbols.h
- include/xmlsec/gnutls/symbols.h
- include/xmlsec/mscng/symbols.h
- include/xmlsec/mscrypto/symbols.h
- include/xmlsec/nss/symbols.h
- include/xmlsec/openssl/symbols.h
See discussion in the issue #935
> Remove alorithm defines that are not implemented by the library

- src/errors.c
to move it out of the .data table
> const up xmlSecErrorsTable

- src/xmltree.c
> Fix build for LibXML2 > 2.15.0
